spring.application.name=montessori
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/montessori
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
app.frontend.url=${FRONTEND_URL}
app.principal.email=${PRINCIPAL_EMAIL}
app.principal.password=${PRINCIPAL_PASSWORD}
app.principal.name=${PRINCIPAL_NAME}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
app.upload.dir=${UPLOAD_DIR}
mnotify.api.key=${MNOTIFY_API_KEY:}
mnotify.sender.id=${MNOTIFY_SENDER_ID:FransgiddyRS}
